---
title: "My Fancy Presentation"
author: "Csaba"
date: '2021 03 15 '
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## My new slide

*italics*

### Subtitle

**boldface**

- item one
- item two

1. numbered item one
2. numbered item two

`a <- 3 + 2`


## R code

```{r comment = "", echo = TRUE, eval = TRUE}
head(mtcars)
```


## Plot

```{r}
plot(mtcars$wt, mtcars$mpg, xlab = "weight", ylab = "mpg")
```

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

